name: Ticket Notification Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  ticket_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 여기에 yfinance가 정확히 포함되어 있는지 확인하세요
          python -m pip install requests beautifulsoup4 python-telegram-bot yfinance

      - name: Run All Scripts
        env:
          KMA_API_KEY: ${{ secrets.KMA_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          # 라이브러리 설치 확인용 (디버깅)
          python -m pip list | grep yfinance || echo "yfinance not found"
          
          python test.py || echo "⚠️ test.py failed but continuing..."
          python ticket_gh.py
