name: Ticket Notification Bot

on:
  workflow_dispatch:      # 수동 실행 버튼
  schedule:
    - cron: '0 23 * * *'  # 한국 시간 오전 08:00 (UTC 23:00)

jobs:
  ticket_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # yfinance를 목록에 추가했습니다.
          python -m pip install requests beautifulsoup4 python-telegram-bot yfinance

      - name: Run All Scripts
        env:
          KMA_API_KEY: ${{ secrets.KMA_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          # test.py 실행 (실패해도 ticket_gh.py는 실행됨)
          python test.py || echo "⚠️ test.py 실행 중 문제가 발생했지만 계속 진행합니다."
          
          # ticket_gh.py 실행
          python ticket_gh.py
