name: Ticket Notification Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  ticket_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests beautifulsoup4 python-telegram-bot yfinance

      - name: Run All Scripts
        env:
          KMA_API_KEY: ${{ secrets.KMA_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python test.py || echo "test.py execution failed"
          python ticket_gh.py
